# dirbs core url
dirbs_core:
  BaseUrl: 'http://192.168.100.89:5000/api'
  Version: v2

# dvs global configurations
global:

  # tac length
  TacLength: 8

  # minimum and maximum global imei lengths
  MinImeiLength: 14
  MaxImeiLength: 16

  # minimum and maximum imei range
  MinImeiRange: '000000'
  MaxImeiRange: 100000  # TODO: change it to 1000000 after testing

  ChunkSize: 10000  # there will be ChunkSize/MaxImeiRange number of threads

  # variables to be configured
  HelpUrl: 'not confirmed'
  BlockDate: 'to be decided'

  # minimum and maximum file content length
  MinFileContent: 0
  MaxFileContent: 1000000

allowed_file_types:

  # allowed file extensions
  AllowedExt: ['tsv', 'txt']

application_root:

  # application root url
  RootUrl: '/api/v1'
  ServerIP: '192.168.100.74'

# celery configurations
celery:

  RabbitmqUrl: 'pyamqp://'
  RabbitmqBackend: 'amqp://'

  RedisUrl: 'redis://'
  RedisBackend: 'redis://'

  RpcUrl: 'rpc://'
  RpcBackend: 'rpc://'

  CeleryTasks: ['app.api.v1.helpers.scheduled', 'app.api.v1.helpers.bulk_summary']